FROM feixiao/cpp_build_20:1.0

LABEL maintainer="frank<feixiao2020@sina.com>"


RUN apt install python
RUN apt install -y file  gnupg flex bison gperf zip curl 
RUN apt update && apt install -y openjdk-11-jdk openjdk-11-jre
#WORKDIR /var/aosp
