FROM ubuntu:25.04


LABEL maintainer="frank<feixiao2020@sina.com>"


#ADD sources.list /etc/apt/sources.list

RUN apt update -y && apt install -y gcc g++  cmake build-essential

RUN apt install -y vim curl gdb git wget 

