FROM feixiao/workbench_2504:1.0

LABEL maintainer="frank"

# RUN /opt/conda/bin/conda create --name hikyuu python=3.10 
# RUN /opt/conda/bin/conda init zsh  && /opt/conda/bin/conda activate hikyuu
# RUN /opt/conda/bin/conda install jupyter_server jupyter notebook